// A finished kit's email swipes become a DRAFT sequence, the way its article becomes a draft post.
//
// campaigns.email_md was generated by every build and then sat there: nothing created a
// broadcast_sequences row, so the copy was only reachable by drilling into the product page's
// Emails tab. Same gap the blog had before createPostFromCampaign, and the same fix.
//
// DRAFT, never active — this is machine-written copy about someone else's product, aimed at real
// people's inboxes. Activating it is the operator's explicit action, exactly as publishing the
// generated blog post is.

import type { SupabaseClient } from "@supabase/supabase-js";

export type ParsedEmail = { subject: string; body_md: string };

const MAX_SUBJECT = 200;

/**
 * Splits a generated `email_md` blob into individual emails.
 *
 * Written against the REAL stored copy across all 14 campaigns, not a guessed format, because the
 * model emits two shapes and a parser tuned to one would silently produce a single malformed email
 * for the other:
 *
 *   "## Email 2 — Subject: Last call — 60-day guarantee either way"   (subject on the heading)
 *   "## Email 1\n\n**Subject:** The weird reason ancient teeth…"      (subject on the next line)
 *
 * Heading level varies too (`##` and `###` both occur). Anything it can't identify a subject for
 * still becomes an email with a derived subject rather than being dropped — losing generated copy
 * silently is worse than an imperfect subject line the operator can edit before sending.
 */
export function parseEmailMd(md: string): ParsedEmail[] {
  if (!md || !md.trim()) return [];

  // Split on the email headings, keeping each heading with its body.
  const parts = md.split(/(?=^#{1,4}\s*Email\s*\d+)/gim).filter((p) => p.trim());
  const emails: ParsedEmail[] = [];

  for (const part of parts) {
    const lines = part.split("\n");
    const heading = lines[0] ?? "";
    if (!/^#{1,4}\s*Email\s*\d+/i.test(heading)) continue;

    // Shape 1: subject on the heading line, after an em dash / hyphen / colon.
    let subject = "";
    const onHeading = heading.match(/Subject\s*:\s*(.+?)\s*$/i);
    if (onHeading) subject = onHeading[1];

    let body = lines.slice(1).join("\n");

    // Shape 2: a "**Subject:** …" line in the body. Removed from the body once used — otherwise
    // the subject would be printed again as the first line of the email.
    if (!subject) {
      const inBody = body.match(/^\s*(?:\*\*|__)?\s*Subject\s*:?\s*(?:\*\*|__)?\s*(.+?)\s*$/im);
      if (inBody) {
        subject = inBody[1].replace(/^\*\*|\*\*$/g, "").trim();
        body = body.replace(inBody[0], "");
      }
    }

    body = body.replace(/^\s+/, "").trimEnd();
    if (!subject) {
      // Last resort: the first non-empty body line, trimmed of markdown. Never empty — subject is
      // NOT NULL on broadcast_steps.
      const firstLine = body.split("\n").find((l) => l.trim()) ?? "";
      subject = firstLine.replace(/^[#>*\-\s]+/, "").trim() || `Email ${emails.length + 1}`;
    }

    if (!body.trim()) continue; // a heading with no body is not an email
    emails.push({ subject: subject.slice(0, MAX_SUBJECT), body_md: body });
  }

  return emails;
}

/**
 * Creates (or refreshes) the draft sequence for a campaign's generated emails.
 *
 * Written with the ADMIN client and explicit workspace_id/user_id, exactly like
 * createPostFromCampaign: the RPCs that normally create sequences are `authenticated`-facing and
 * key off auth.uid(), which is NULL for the service-role worker.
 *
 * Idempotent on source_campaign_id, so a rebuild refreshes the draft rather than stacking a second
 * one. A sequence the operator has already ACTIVATED is left completely alone — overwriting steps
 * of a live drip would change what already-enrolled contacts are about to receive.
 *
 * The audience is that campaign's own contacts (`audience_type: 'campaign'`), which is both the
 * obviously-right audience for an offer's follow-up and why the existing campaign_id column is a
 * good fit — it means the same thing here as everywhere else.
 */
export async function createSequenceFromCampaign(
  admin: SupabaseClient,
  workspaceId: string,
  campaignId: string
): Promise<{ created: boolean; steps: number } | null> {
  const { data: campaign } = await admin
    .from("campaigns")
    .select("id, user_id, email_md, product_id, name, products(product_title)")
    .eq("id", campaignId)
    .eq("workspace_id", workspaceId)
    .maybeSingle();
  if (!campaign?.email_md) return null;

  const emails = parseEmailMd(campaign.email_md as string);
  if (emails.length === 0) return null;

  const title =
    ((campaign as any).products?.product_title as string | undefined) ??
    ((campaign as any).name as string | null) ??
    "Campaign";
  const name = `${title} — follow-up`.slice(0, 120);

  const { data: existing } = await admin
    .from("broadcast_sequences")
    .select("id, status")
    .eq("workspace_id", workspaceId)
    .eq("source_campaign_id", campaignId)
    .maybeSingle();

  // Never touch a sequence that is live or paused mid-flight — contacts are already enrolled
  // against these exact steps.
  if (existing && existing.status !== "draft") return { created: false, steps: 0 };

  let sequenceId = existing?.id as string | undefined;
  if (!sequenceId) {
    const { data: inserted, error } = await admin
      .from("broadcast_sequences")
      .insert({
        workspace_id: workspaceId,
        // Created-by attribution for a derived row, same call createPostFromCampaign makes.
        user_id: campaign.user_id,
        name,
        kind: "sequence",
        status: "draft",
        audience_type: "campaign",
        campaign_id: campaignId,
        source_campaign_id: campaignId,
      })
      .select("id")
      .single();
    if (error) throw error;
    sequenceId = inserted.id as string;
  } else {
    // A rebuild replaces the draft's steps wholesale — simplest-correct, and the draft has no
    // enrollments by definition.
    await admin.from("broadcast_steps").delete().eq("sequence_id", sequenceId);
  }

  const rows = emails.map((e, i) => ({
    workspace_id: workspaceId,
    user_id: campaign.user_id,
    sequence_id: sequenceId,
    step_index: i + 1,
    // Day 0, then every 2 days — a starting cadence to edit, not a recommendation. Sending all of
    // them at once would be the only worse default.
    delay_days: i === 0 ? 0 : i * 2,
    subject: e.subject,
    body_md: e.body_md,
  }));
  const { error: stepErr } = await admin.from("broadcast_steps").insert(rows);
  if (stepErr) throw stepErr;

  return { created: !existing, steps: rows.length };
}

/**
 * Creates (or refreshes) the draft SMS drip for a campaign's generated messages.
 *
 * The exact treatment the kit's emails get above, for the same reason: `campaigns.sms_messages`
 * (0096) was generated and then sat unreachable outside the product page's SMS tab, while the
 * whole drip machinery — channel-aware enrollment, consent enforcement, quiet hours — was already
 * built and waiting for rows. 0105 widened the one-per-source-campaign index to include channel,
 * so this and the email draft coexist for the same campaign.
 *
 * DRAFT, never active, and doubly so here: an unwanted email is an annoyance, an unwanted text is
 * a TCPA claim. Activating stays the operator's explicit act, behind the Twilio-connection gate.
 *
 * No parsing step — sms_messages was structured from day one ([{ body }]) precisely to avoid
 * repeating the email_md reverse-engineering this file's parseEmailMd exists to do.
 */
export async function createSmsSequenceFromCampaign(
  admin: SupabaseClient,
  workspaceId: string,
  campaignId: string
): Promise<{ created: boolean; steps: number } | null> {
  const { data: campaign } = await admin
    .from("campaigns")
    .select("id, user_id, sms_messages, product_id, name, products(product_title)")
    .eq("id", campaignId)
    .eq("workspace_id", workspaceId)
    .maybeSingle();

  const messages = (Array.isArray(campaign?.sms_messages) ? campaign!.sms_messages : []) as {
    body?: string;
  }[];
  const bodies = messages.map((m) => (typeof m?.body === "string" ? m.body.trim() : "")).filter(Boolean);
  if (bodies.length === 0) return null;

  const title =
    ((campaign as any).products?.product_title as string | undefined) ??
    ((campaign as any).name as string | null) ??
    "Campaign";
  const name = `${title} — SMS drip`.slice(0, 120);

  const { data: existing } = await admin
    .from("broadcast_sequences")
    .select("id, status")
    .eq("workspace_id", workspaceId)
    .eq("source_campaign_id", campaignId)
    .eq("channel", "sms")
    .maybeSingle();

  // Never touch a sequence that is live or paused mid-flight — contacts are already enrolled
  // against these exact steps, and for SMS a silently changed step is a compliance problem, not
  // just a surprise.
  if (existing && existing.status !== "draft") return { created: false, steps: 0 };

  let sequenceId = existing?.id as string | undefined;
  if (!sequenceId) {
    const { data: inserted, error } = await admin
      .from("broadcast_sequences")
      .insert({
        workspace_id: workspaceId,
        user_id: campaign!.user_id,
        name,
        kind: "sequence",
        channel: "sms",
        status: "draft",
        audience_type: "campaign",
        campaign_id: campaignId,
        source_campaign_id: campaignId,
      })
      .select("id")
      .single();
    if (error) throw error;
    sequenceId = inserted.id as string;
  } else {
    await admin.from("broadcast_steps").delete().eq("sequence_id", sequenceId);
  }

  const rows = bodies.map((body, i) => ({
    workspace_id: workspaceId,
    user_id: campaign!.user_id,
    sequence_id: sequenceId,
    step_index: i + 1,
    // Texts are pushier than email by nature, so the default cadence is SLOWER: day 0, then every
    // 3 days. A starting point to edit, same as the email default above.
    delay_days: i === 0 ? 0 : i * 3,
    // broadcast_steps.subject is NOT NULL and never sent for sms — the internal-label convention
    // 0098 established.
    subject: `Message ${i + 1}`,
    body_md: body,
  }));
  const { error: stepErr } = await admin.from("broadcast_steps").insert(rows);
  if (stepErr) throw stepErr;

  return { created: !existing, steps: rows.length };
}
