import type { MetadataRoute } from "next";
import { headers } from "next/headers";
import { APP_URL } from "@/lib/appUrl";
import { classifyHost } from "@/lib/host";

// Crawl policy: marketing pages and public blog posts (/b/) are indexable; everything auth-gated
// or tenant-specific is disallowed. Funnel pages (/p/, /d/) additionally send X-Robots-Tag:
// noindex from their own routes — disallowing them here too keeps crawlers from even fetching.
//
// ONLY THE CANONICAL HOST IS CRAWLABLE, and this file has to decide that itself. The rules below
// are host-independent — `Allow: /` plus a Sitemap line built from APP_URL — so whichever host
// serves them invites indexing of the whole marketing site under THAT origin. That really happened:
// while NEXT_PUBLIC_APP_URL still named the raw *.netlify.app hostname (necessarily, before the
// domain was attached), the site was fully crawlable there, publishing a sitemap listing every
// marketing page under an autogenerated Netlify name alongside the real brand domain.
//
// Correcting the env var fixed it incidentally — a non-canonical host now classifies as `custom`
// and middleware rewrites it to /d, where nothing matches. That safety is a side effect of one
// environment variable being right, which is not where a duplicate-content control belongs. So it
// is stated explicitly here, and it also covers the case the rewrite does NOT catch: a workspace
// subdomain classifies as `workspace`, not `custom`, so it is never rewritten and would otherwise
// serve this file verbatim. Same reasoning as the X-Robots-Tag: noindex middleware already sets on
// /b/* for workspace hosts — the canonical host stays the indexable one.
//
// Fails CLOSED: an absent or unrecognised Host classifies as `custom`, which is not `app`, so the
// restrictive answer is the default.
//
// NOT the fix for the netlify.app hostname: redirecting it wholesale would break the four Vault
// cron URLs that POST there, since pg_net does not follow redirects — a 3xx is a failed delivery,
// the same silent class as a Stripe webhook registered on www.
export default function robots(): MetadataRoute.Robots {
  if (classifyHost(headers().get("host")).kind !== "app") {
    return { rules: [{ userAgent: "*", disallow: "/" }] };
  }

  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: [
          "/api/",
          "/dashboard",
          "/marketplace",
          "/funnels",
          "/settings/integrations",
          "/settings/domains",
          "/contacts",
          "/emails",
          "/blog",
          "/audit",
          "/settings/billing",
          "/product/",
          "/login",
          "/p/",
          "/d/",
        ],
      },
    ],
    sitemap: `${APP_URL}/sitemap.xml`,
  };
}
