"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import Link from "next/link";
import { Bell, CheckCheck, AlertTriangle, Sparkles, Gift, Globe, Mail } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Notification = {
  id: string;
  kind: string;
  title: string;
  body: string | null;
  href: string | null;
  read_at: string | null;
  created_at: string;
};

const KIND_ICON: Record<string, typeof Bell> = {
  job_failed: AlertTriangle,
  campaign_ready: Sparkles,
  referral_rewarded: Gift,
  domain_error: Globe,
  mail_sender_error: Mail,
};

const KIND_TONE: Record<string, string> = {
  job_failed: "text-red-300",
  campaign_ready: "text-emerald-300",
  referral_rewarded: "text-emerald-300",
  domain_error: "text-amber-300",
  mail_sender_error: "text-amber-300",
};

const PAGE_SIZE = 20;
// Polled rather than realtime-subscribed: notifications are generated by background jobs that
// take tens of seconds to minutes, so a websocket buys nothing here and this app has no other
// realtime usage to amortize the connection against.
const POLL_MS = 60_000;

function relativeTime(iso: string): string {
  const diff = Date.now() - new Date(iso).getTime();
  const mins = Math.floor(diff / 60_000);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins}m ago`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return `${hours}h ago`;
  return `${Math.floor(hours / 24)}d ago`;
}

export default function NotificationsBell({ iconOnly = false }: { iconOnly?: boolean }) {
  const [items, setItems] = useState<Notification[]>([]);
  const [open, setOpen] = useState(false);
  // The panel renders in a portal because the sidebar that hosts this button is a scroll
  // container (`sm:overflow-y-auto`) narrower than the panel — an absolutely-positioned dropdown
  // gets clipped at the sidebar's edge. Anchoring to the button's measured rect keeps it visually
  // attached while escaping that clip entirely.
  const [anchor, setAnchor] = useState<{ top: number; left: number } | null>(null);
  const wrapRef = useRef<HTMLDivElement>(null);
  const btnRef = useRef<HTMLButtonElement>(null);
  const panelRef = useRef<HTMLDivElement>(null);

  const load = useCallback(async () => {
    // RLS scopes this to the caller — no user_id filter needed, and none is trusted from here.
    const { data } = await createClient()
      .from("notifications")
      .select("id, kind, title, body, href, read_at, created_at")
      .order("created_at", { ascending: false })
      .limit(PAGE_SIZE);
    setItems((data as Notification[]) ?? []);
  }, []);

  useEffect(() => {
    load();
    const t = setInterval(load, POLL_MS);
    return () => clearInterval(t);
  }, [load]);

  // Close on outside click / Escape — a dropdown that traps the page is worse than no dropdown.
  useEffect(() => {
    if (!open) return;
    function onDown(e: MouseEvent) {
      const t = e.target as Node;
      // The panel lives outside wrapRef (portal), so both roots must be checked.
      if (wrapRef.current?.contains(t) || panelRef.current?.contains(t)) return;
      setOpen(false);
    }
    function onKey(e: KeyboardEvent) {
      if (e.key === "Escape") setOpen(false);
    }
    document.addEventListener("mousedown", onDown);
    document.addEventListener("keydown", onKey);
    return () => {
      document.removeEventListener("mousedown", onDown);
      document.removeEventListener("keydown", onKey);
    };
  }, [open]);

  const unread = items.filter((n) => !n.read_at).length;

  async function markAllRead() {
    // Optimistic: the panel is already open and the user is looking at it, so waiting on a round
    // trip to grey the badge just feels broken. Re-loaded below to reconcile.
    const now = new Date().toISOString();
    setItems((prev) => prev.map((n) => (n.read_at ? n : { ...n, read_at: now })));
    await createClient().rpc("mark_notifications_read", { p_ids: null });
    load();
  }

  async function markOneRead(id: string) {
    setItems((prev) =>
      prev.map((n) => (n.id === id && !n.read_at ? { ...n, read_at: new Date().toISOString() } : n))
    );
    await createClient().rpc("mark_notifications_read", { p_ids: [id] });
  }

  return (
    <div ref={wrapRef} className="relative">
      <button
        ref={btnRef}
        onClick={() => {
          const r = btnRef.current?.getBoundingClientRect();
          if (r) {
            const width = Math.min(320, window.innerWidth - 16);
            // Clamp to the viewport so the panel never hangs off-screen on a narrow window.
            setAnchor({
              top: r.bottom + 8,
              left: Math.min(Math.max(8, r.left), window.innerWidth - width - 8),
            });
          }
          setOpen((o) => !o);
        }}
        title={unread > 0 ? `${unread} unread notification${unread === 1 ? "" : "s"}` : "Notifications"}
        aria-label={unread > 0 ? `Notifications, ${unread} unread` : "Notifications"}
        className={`relative flex items-center gap-1.5 rounded-lg p-1.5 text-zinc-400 hover:bg-ink-800 hover:text-zinc-200 ${
          iconOnly ? "justify-center" : ""
        }`}
      >
        <Bell className="h-4 w-4 shrink-0" />
        {unread > 0 && (
          <span className="absolute -right-0.5 -top-0.5 flex h-4 min-w-4 items-center justify-center rounded-full bg-emerald-500 px-1 text-[10px] font-semibold leading-none text-white">
            {unread > 9 ? "9+" : unread}
          </span>
        )}
      </button>

      {open && anchor && createPortal(
        <div
          ref={panelRef}
          style={{ top: anchor.top, left: anchor.left }}
          className="fixed z-50 w-80 max-w-[calc(100vw-1rem)] overflow-hidden rounded-xl border border-ink-600 bg-ink-900 shadow-xl"
        >
          <div className="flex items-center justify-between border-b border-ink-700 px-3 py-2">
            <span className="text-xs font-semibold uppercase tracking-wide text-zinc-400">
              Notifications
            </span>
            {unread > 0 && (
              <button
                onClick={markAllRead}
                className="flex items-center gap-1 text-xs text-zinc-400 hover:text-emerald-300"
              >
                <CheckCheck className="h-3.5 w-3.5" /> Mark all read
              </button>
            )}
          </div>

          <div className="max-h-96 overflow-y-auto">
            {items.length === 0 ? (
              <p className="px-3 py-8 text-center text-xs text-zinc-500">
                Nothing yet. You&apos;ll hear about failed jobs, finished campaign kits, and
                referral rewards here.
              </p>
            ) : (
              items.map((n) => {
                const Icon = KIND_ICON[n.kind] ?? Bell;
                const tone = KIND_TONE[n.kind] ?? "text-zinc-400";
                const inner = (
                  <div
                    className={`flex gap-2.5 px-3 py-2.5 ${n.read_at ? "opacity-60" : ""} hover:bg-ink-800`}
                  >
                    <Icon className={`mt-0.5 h-4 w-4 shrink-0 ${tone}`} />
                    <div className="min-w-0 flex-1">
                      <div className="flex items-start gap-2">
                        <span className="flex-1 text-sm text-zinc-100">{n.title}</span>
                        {!n.read_at && (
                          <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-emerald-400" />
                        )}
                      </div>
                      {n.body && (
                        <p className="mt-0.5 line-clamp-2 text-xs text-zinc-500">{n.body}</p>
                      )}
                      <span className="mt-0.5 block text-[11px] text-zinc-600">
                        {relativeTime(n.created_at)}
                      </span>
                    </div>
                  </div>
                );
                return n.href ? (
                  <Link
                    key={n.id}
                    href={n.href}
                    onClick={() => {
                      markOneRead(n.id);
                      setOpen(false);
                    }}
                    className="block border-b border-ink-800 last:border-0"
                  >
                    {inner}
                  </Link>
                ) : (
                  <button
                    key={n.id}
                    onClick={() => markOneRead(n.id)}
                    className="block w-full border-b border-ink-800 text-left last:border-0"
                  >
                    {inner}
                  </button>
                );
              })
            )}
          </div>
        </div>,
        document.body
      )}
    </div>
  );
}
