// ClickBank marketplace category taxonomy — pulled live from the marketplace GraphQL facets
// endpoint on 2026-07-22 (facets scoped per top-level category). Marketplace categories rarely
// change; refresh by re-running the same facets query per category if this ever drifts.

export type Category = {
  name: string;
  subCategories: string[];
};

export const CLICKBANK_CATEGORIES: Category[] = [
  { name: "Arts & Entertainment", subCategories: ["Art", "Body Art", "General", "Music"] },
  { name: "Betting Systems", subCategories: ["Football", "General", "Horse Racing", "Soccer"] },
  {
    name: "Business / Investing",
    subCategories: [
      "Careers, Industries & Professions",
      "Equities & Stocks",
      "Foreign Exchange",
      "General",
      "International Business",
      "Management & Leadership",
      "Marketing & Sales",
      "Personal Finance",
      "Real Estate",
      "Small Biz / Entrepreneurship",
    ],
  },
  { name: "Computers / Internet", subCategories: ["General", "Graphics", "Web Site Design"] },
  { name: "Cooking, Food & Wine", subCategories: ["BBQ", "Cooking", "Recipes", "Special Diet"] },
  {
    name: "E-business & E-marketing",
    subCategories: [
      "Affiliate Marketing",
      "Article Marketing",
      "Banners",
      "Blog Marketing",
      "Consulting",
      "Copywriting",
      "E-commerce Operations",
      "Email Marketing",
      "General",
      "Marketing",
      "Niche Marketing",
      "Social Media Marketing",
      "Video Marketing",
    ],
  },
  { name: "E-Commerce", subCategories: ["General"] },
  { name: "Education", subCategories: ["Educational Materials", "Test Prep & Study Guides"] },
  {
    name: "Employment & Jobs",
    subCategories: ["General", "Job Listings", "Job Search Guides", "Job Skills / Training"],
  },
  { name: "Games", subCategories: ["General", "Strategy Guides"] },
  {
    name: "Green Products",
    subCategories: ["Alternative Energy", "Conservation & Efficiency", "General"],
  },
  {
    name: "Health & Fitness",
    subCategories: [
      "Addiction",
      "Beauty",
      "Dental Health",
      "Dietary Supplements",
      "Diets & Weight Loss",
      "Exercise & Fitness",
      "General",
      "Meditation",
      "Men's Health",
      "Mental Health",
      "Nutrition",
      "Remedies",
      "Sleep and Dreams",
      "Spiritual Health",
      "Strength Training",
      "Women's Health",
      "Yoga",
    ],
  },
  {
    name: "Home & Garden",
    subCategories: [
      "Animal Care & Pets",
      "Crafts & Hobbies",
      "Gardening & Horticulture",
      "General",
      "Homebuying",
      "How-to & Home Improvements",
    ],
  },
  { name: "Languages", subCategories: ["Italian", "Other"] },
  {
    name: "Parenting & Families",
    subCategories: ["Divorce", "Education", "General", "Parenting", "Pregnancy & Childbirth"],
  },
  { name: "Politics / Current Events", subCategories: ["General"] },
  { name: "Reference", subCategories: ["Automotive", "Catalogs & Directories"] },
  {
    name: "Self-Help",
    subCategories: [
      "Dating Guides",
      "Eating Disorders",
      "General",
      "Marriage & Relationships",
      "Motivational / Transformational",
      "Personal Finance",
      "Public Speaking",
      "Self Defense",
      "Self-Esteem",
      "Stress Management",
      "Success",
      "Survival",
      "Time Management",
    ],
  },
  {
    name: "Software & Services",
    subCategories: [
      "Email",
      "Foreign Exchange Investing",
      "General",
      "Graphic Design",
      "Internet Tools",
      "Other Investment Software",
      "Personal Finance",
      "Productivity",
      "Video",
    ],
  },
  {
    name: "Spirituality, New Age & Alternative Beliefs",
    subCategories: [
      "Astrology",
      "General",
      "Hypnosis",
      "Magic",
      "Numerology",
      "Psychics",
      "Religion",
      "Tarot",
      "Witchcraft",
    ],
  },
  {
    name: "Sports",
    subCategories: [
      "Automotive",
      "Cycling",
      "General",
      "Golf",
      "Racket Sports",
      "Running",
      "Soccer",
      "Training",
      "Water Sports",
    ],
  },
  { name: "Travel", subCategories: ["General", "Specialty Travel", "United States"] },
];
